(() => {
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const mini=document.getElementById('minimap'),mctx=mini.getContext('2d');
const $=id=>document.getElementById(id),resourceEl=$('resource'),unitCountEl=$('unitCount'),msgEl=$('message'),nameEl=$('selectedName'),infoEl=$('selectedInfo'),counterEl=$('counterInfo');
const btn={worker:$('btnWorker'),sword:$('btnSword'),spear:$('btnSpear'),archer:$('btnArcher'),cavalry:$('btnCavalry'),farm:$('btnFarm'),tower:$('btnTower'),gather:$('btnGather'),mine:$('btnMine'),attack:$('btnAttack')};
const DPR=Math.max(1,Math.min(3,devicePixelRatio||1));let W=0,H=0,MW=0,MH=0,lastPointer=null;
const state={resource:220,selected:[],mode:'normal',camera:{x:650,y:500,zoom:1},mapW:2600,mapH:1800,last:0,enemyTimer:0,gameOver:false,drag:null,cap:60};
const units=[],objects=[],fx=[];
const labels={worker:['Worker','gathering','combat'],sword:['Swordsman','Spearmen','Archers'],spear:['Spearman','Cavalry','Swordsmen'],archer:['Archer','Swordsmen','Cavalry'],cavalry:['Cavalry','Archers','Spearmen'],raider:['Dark Sword','Spearmen','Archers'],impaler:['Dark Spear','Cavalry','Swordsmen'],darkarcher:['Dark Archer','Swordsmen','Cavalry'],warg:['Warg Rider','Archers','Spearmen']};
const matrix={sword:{spear:1.5,archer:.5},spear:{cavalry:1.5,sword:.5},archer:{sword:1.5,cavalry:.5},cavalry:{archer:1.5,spear:.5}};
function ctype(t){return {raider:'sword',impaler:'spear',darkarcher:'archer',warg:'cavalry'}[t]||t}
function mod(a,t){return (matrix[ctype(a.type)]&&matrix[ctype(a.type)][ctype(t.type)])||1}
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);MW=mini.clientWidth;MH=mini.clientHeight;mini.width=MW*DPR;mini.height=MH*DPR;mctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function rand(a,b){return a+Math.random()*(b-a)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function msg(t){msgEl.textContent=t}
function s2w(x,y){return{x:(x-W/2)/state.camera.zoom+state.camera.x,y:(y-H/2)/state.camera.zoom+state.camera.y}}function w2s(x,y){return{x:(x-state.camera.x)*state.camera.zoom+W/2,y:(y-state.camera.y)*state.camera.zoom+H/2}}
function addObj(o){objects.push(o);return o}function addUnit(u){if(u.team==='player'&&playerUnits().length>=state.cap){msg('Unit cap reached.');return null}u=Object.assign({selected:false,tx:u.x,ty:u.y,hp:u.maxHp,cool:0,task:'idle',target:null},u);units.push(u);return u}
const keep=addObj({type:'keep',team:'player',name:'Stonehall Keep',x:600,y:470,r:72,hp:900,maxHp:900});
addObj({type:'farm',team:'player',name:'Farm',x:760,y:555,r:48,hp:330,maxHp:330,timer:0});
const camp=addObj({type:'camp',team:'enemy',name:'Dark Legion Camp',x:2050,y:1150,r:86,hp:780,maxHp:780});
addObj({type:'slaughterhouse',team:'enemy',name:'Slaughterhouse',x:1935,y:1290,r:55,hp:360,maxHp:360,timer:0});
[['worker',485,515],['worker',530,565],['sword',655,505],['spear',690,535],['archer',710,450],['cavalry',610,620]].forEach(([t,x,y])=>spawnPlayer(t,x,y));
[['raider',1940,1080],['impaler',1990,1055],['darkarcher',2080,1240],['warg',2150,1090]].forEach(([t,x,y])=>spawnEnemy(t,x,y));
function spawnPlayer(type,x,y){const spec={worker:{name:'Worker',r:16,speed:98,maxHp:80,attack:5,range:24},sword:{name:'Swordsman',r:18,speed:84,maxHp:150,attack:19,range:32},spear:{name:'Spearman',r:18,speed:82,maxHp:135,attack:17,range:38},archer:{name:'Archer',r:16,speed:88,maxHp:92,attack:14,range:185},cavalry:{name:'Cavalry',r:24,speed:128,maxHp:175,attack:22,range:38}}[type];return addUnit(Object.assign({type,team:'player',x,y},spec))}
function spawnEnemy(type,x,y){const spec={raider:{name:'Dark Swordsman',r:18,speed:76,maxHp:125,attack:16,range:31},impaler:{name:'Dark Spearman',r:18,speed:74,maxHp:125,attack:15,range:38},darkarcher:{name:'Dark Archer',r:16,speed:80,maxHp:86,attack:13,range:170},warg:{name:'Warg Rider',r:24,speed:118,maxHp:160,attack:20,range:38}}[type];return addUnit(Object.assign({type,team:'enemy',x,y},spec))}
function cluster(cx,cy,n,spread){for(let i=0;i<n;i++){let a=rand(0,Math.PI*2),rr=Math.pow(Math.random(),.65)*spread;addObj({type:'tree',team:'neutral',x:clamp(cx+Math.cos(a)*rr+rand(-20,20),80,state.mapW-80),y:clamp(cy+Math.sin(a)*rr+rand(-20,20),80,state.mapH-80),r:rand(20,38),resource:rand(55,90),maxResource:90,var:Math.floor(rand(0,3))})}}
cluster(300,320,20,230);cluster(520,1080,18,250);cluster(1150,310,16,260);cluster(1450,1420,18,260);cluster(2300,420,15,220);
[[420,1325,520],[1240,820,620],[2220,520,580]].forEach(([x,y,res])=>addObj({type:'mine',team:'neutral',name:'Resource Mine',x,y,r:58,resource:res,maxResource:res}));
function playerUnits(){return units.filter(u=>u.team==='player'&&u.hp>0)}
function hit(w,team){let a=[];for(const u of units)if(u.hp>0&&(!team||u.team===team)&&Math.hypot(u.x-w.x,u.y-w.y)<=u.r+12)a.push(u);for(const o of objects)if((o.hp===undefined||o.hp>0)&&(!team||o.team===team)&&Math.hypot(o.x-w.x,o.y-w.y)<=o.r+10)a.push(o);return a.sort((x,y)=>(x.r||20)-(y.r||20))[0]||null}
function select(list){units.forEach(u=>u.selected=false);state.selected=list.filter(u=>u&&u.team==='player'&&u.hp>0);state.selected.forEach(u=>u.selected=true);msg(state.selected.length===1?`${state.selected[0].name} selected.`:`${state.selected.length} units selected.`);updateCard()}
function updateCard(){state.selected=state.selected.filter(u=>u.hp>0);if(!state.selected.length){nameEl.textContent='No unit selected';infoEl.textContent='Tap or two-finger drag select.';counterEl.textContent='Spear > Cavalry > Archer > Swordsman > Spear';return}if(state.selected.length===1){let u=state.selected[0],l=labels[u.type]||[u.name,'-','-'];nameEl.textContent=l[0];infoEl.textContent=`HP ${Math.max(0,Math.floor(u.hp))}/${u.maxHp} • ${u.task}`;counterEl.textContent=`Strong vs ${l[1]} • Weak vs ${l[2]}`;return}let c={};state.selected.forEach(u=>c[u.type]=(c[u.type]||0)+1);nameEl.textContent=`${state.selected.length} units selected`;infoEl.textContent=Object.entries(c).map(([k,v])=>`${v} ${labels[k]?.[0]||k}`).join(' • ');counterEl.textContent='Mixed army selected. Use counters to win fights.'}
function nearest(u,type){let best=null,bd=1e9;for(const o of objects){if(o.type!==type)continue;if((type==='tree'||type==='mine')&&(o.resource||0)<=0)continue;if(o.hp!==undefined&&o.hp<=0)continue;let d=Math.hypot(o.x-u.x,o.y-u.y);if(d<bd){bd=d;best=o}}return best}
function nearestEnemy(u){let best=null,bd=1e9;for(const v of units)if(v.team!==u.team&&v.hp>0){let d=Math.hypot(v.x-u.x,v.y-u.y);if(d<bd){bd=d;best=v}}for(const o of objects)if(o.team!==u.team&&o.team!=='neutral'&&o.hp>0){let d=Math.hypot(o.x-u.x,o.y-u.y);if(d<bd){bd=d;best=o}}return best}
function nearestPlayer(u){let best=keep,bd=1e9;for(const v of units)if(v.team==='player'&&v.hp>0){let d=Math.hypot(v.x-u.x,v.y-u.y);if(d<bd){bd=d;best=v}}for(const o of objects)if(o.team==='player'&&o.hp>0){let d=Math.hypot(o.x-u.x,o.y-u.y);if(d<bd){bd=d;best=o}}return best}
function moveGroup(x,y){let s=state.selected;if(!s.length)return msg('Select units first.');let spread=Math.max(30,Math.min(86,s.length*9));s.forEach((u,i)=>{let a=i/Math.max(1,s.length)*Math.PI*2,ring=s.length===1?0:spread;u.tx=clamp(x+Math.cos(a)*ring,40,state.mapW-40);u.ty=clamp(y+Math.sin(a)*ring,40,state.mapH-40);u.task='move';u.target=null});msg(`Moving ${s.length} unit${s.length>1?'s':''}.`)}
function attackGroup(t){if(!state.selected.length)return msg('Select units first.');state.selected.forEach(u=>{u.target=t;u.task='attack'});msg(`Attacking ${t.name||t.type}.`)}
function orderGather(type){let workers=state.selected.filter(u=>u.type==='worker'&&u.hp>0);if(!workers.length)return msg('Select workers first.');workers.forEach(u=>{u.target=nearest(u,type);u.task=u.target?(type==='mine'?'mine':'chop'):'idle'});msg(`${workers.length} worker${workers.length>1?'s':''} ordered to ${type==='mine'?'mine':'chop trees'}.`)}
function train(type){const cost={worker:35,sword:55,spear:50,archer:60,cavalry:90}[type];if(state.resource<cost)return msg(`Need ${cost} Resource.`);state.resource-=cost;let u=spawnPlayer(type,keep.x+rand(-90,90),keep.y+rand(80,120));if(u)select([u]);msg(`${labels[type][0]} trained.`)}
function startPlace(type){const cost=type==='farm'?90:120;if(state.resource<cost)return msg(`Need ${cost} Resource.`);if(!state.selected.some(u=>u.type==='worker'))return msg('Select a worker first.');state.mode='place'+type;msg(`${type==='farm'?'Farm':'Tower'} placement: tap near a worker.`);refresh()}
function place(type,x,y){const cost=type==='farm'?90:120;if(!state.selected.some(u=>u.type==='worker'&&Math.hypot(u.x-x,u.y-y)<280))return msg('Place within worker range.');if(state.resource<cost)return msg(`Need ${cost} Resource.`);state.resource-=cost;addObj(type==='farm'?{type:'farm',team:'player',name:'Farm',x,y,r:48,hp:330,maxHp:330,timer:0}:{type:'tower',team:'player',name:'Watchtower',x,y,r:38,hp:280,maxHp:280,cool:0});state.mode='normal';refresh();msg(`${type==='farm'?'Farm':'Watchtower'} built.`)}
btn.worker.onclick=()=>train('worker');btn.sword.onclick=()=>train('sword');btn.spear.onclick=()=>train('spear');btn.archer.onclick=()=>train('archer');btn.cavalry.onclick=()=>train('cavalry');btn.farm.onclick=()=>startPlace('farm');btn.tower.onclick=()=>startPlace('tower');btn.gather.onclick=()=>orderGather('tree');btn.mine.onclick=()=>orderGather('mine');btn.attack.onclick=()=>{state.mode='attack';msg('Attack mode: tap enemy.');refresh()};
function refresh(){Object.values(btn).forEach(b=>b.classList.remove('active'));if(state.mode==='attack')btn.attack.classList.add('active');if(state.mode==='placefarm')btn.farm.classList.add('active');if(state.mode==='placetower')btn.tower.classList.add('active')}
function deal(t,base,a){if(!t||t.hp===undefined)return;let m=a?mod(a,t):1,amt=base*m;t.hp-=amt;fx.push({x:t.x,y:t.y-(t.r||20),text:`${m>1?'STRONG ':m<1?'WEAK ':''}-${Math.floor(amt)}`,life:.75,kind:'text',m});if(t.hp<=0){if(t===keep){state.gameOver=true;msg('Your keep has fallen. Refresh to restart.')}if(t===camp)msg('Victory! The Dark Legion Camp has fallen.')}}
function move(u,dt){let dx=u.tx-u.x,dy=u.ty-u.y,d=Math.hypot(dx,dy);if(d<1)return;let step=Math.min(d,u.speed*dt);u.x+=dx/d*step;u.y+=dy/d*step;u.x=clamp(u.x,20,state.mapW-20);u.y=clamp(u.y,20,state.mapH-20)}
function gather(u,dt,type){let t=u.target;if(!t||(t.resource||0)<=0){u.target=nearest(u,type==='mine'?'mine':'tree');if(!u.target)u.task='idle';return}let d=Math.hypot(t.x-u.x,t.y-u.y);if(d>u.r+t.r+10){u.tx=t.x;u.ty=t.y;move(u,dt)}else if(u.cool<=0){let g=Math.min(type==='mine'?14:9,t.resource);t.resource-=g;state.resource+=g;u.cool=type==='mine'?1.05:.8;fx.push({x:t.x,y:t.y-t.r,text:`+${Math.floor(g)}`,life:.55,kind:'gain'});if(t.type==='tree'&&t.resource<=0)fx.push({x:t.x,y:t.y,text:'stump',life:.85,kind:'text'})}}
function updateUnit(u,dt){if(u.hp<=0)return;u.cool=Math.max(0,u.cool-dt);if(u.team==='enemy'){u.target=nearestPlayer(u);u.task='attack'}if(u.task==='chop')return gather(u,dt,'tree');if(u.task==='mine')return gather(u,dt,'mine');if(u.task==='attack'){let t=u.target;if(!t||t.hp<=0){t=nearestEnemy(u);u.target=t}if(!t){u.task='idle';return}let d=Math.hypot(t.x-u.x,t.y-u.y);if(d>u.range+(t.r||20)){u.tx=t.x;u.ty=t.y;move(u,dt)}else if(u.cool<=0){deal(t,u.attack,u);u.cool=(u.type==='archer'||u.type==='darkarcher')?1.25:(u.type==='cavalry'||u.type==='warg'?.95:1.05);if(u.range>80)fx.push({x:u.x,y:u.y,tx:t.x,ty:t.y,life:.18,kind:'arrow'})}return}if(u.task==='move'){move(u,dt);if(Math.hypot(u.tx-u.x,u.ty-u.y)<5)u.task='idle'}if(u.team==='player'&&u.task==='idle'&&u.type!=='worker'){let e=nearestEnemy(u);if(e&&Math.hypot(e.x-u.x,e.y-u.y)<u.range+60){u.target=e;u.task='attack'}}}
function updateBuildings(dt){for(const o of objects){if(o.hp!==undefined&&o.hp<=0)continue;if(o.type==='farm'&&o.team==='player'){o.timer+=dt;if(o.timer>=1.6){o.timer=0;state.resource+=6;fx.push({x:o.x,y:o.y-o.r,text:'+6',life:.45,kind:'gain'})}}if(o.type==='slaughterhouse'){o.timer+=dt;if(o.timer>=4.5){o.timer=0;state.enemyTimer+=3.5}}if(o.type==='tower'&&o.team==='player'){o.cool=Math.max(0,(o.cool||0)-dt);let target=null,bd=300;for(const e of units)if(e.team==='enemy'&&e.hp>0){let d=Math.hypot(e.x-o.x,e.y-o.y);if(d<bd){bd=d;target=e}}if(target&&o.cool<=0){deal(target,23,{type:'archer'});o.cool=1.1;fx.push({x:o.x,y:o.y,tx:target.x,ty:target.y,life:.2,kind:'bolt'})}}}}
function spawnWave(dt){if(camp.hp<=0||state.gameOver)return;state.enemyTimer+=dt;if(state.enemyTimer>14){state.enemyTimer=0;let r=Math.random(),t=r<.3?'raider':r<.55?'impaler':r<.8?'darkarcher':'warg';spawnEnemy(t,camp.x+rand(-80,80),camp.y+rand(-80,80));msg('Enemy reinforcements are marching from the Dark Legion Camp.')}}
function update(dt){if(state.gameOver)return;units.forEach(u=>updateUnit(u,dt));updateBuildings(dt);spawnWave(dt);for(let i=fx.length-1;i>=0;i--){fx[i].life-=dt;if(fx[i].life<=0)fx.splice(i,1)}resourceEl.textContent=Math.floor(state.resource);unitCountEl.textContent=playerUnits().length;updateCard()}
function ground(){let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#375523');g.addColorStop(.55,'#263c1d');g.addColorStop(1,'#172714');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(41,94,120,.58)';ctx.lineWidth=52*state.camera.zoom;let a=w2s(1300,-100),b=w2s(1680,1900),c=w2s(1550,420),d=w2s(1200,950);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo(c.x,c.y,d.x,d.y,b.x,b.y);ctx.stroke();ctx.strokeStyle='rgba(108,83,47,.35)';ctx.lineWidth=28*state.camera.zoom;let r1=w2s(460,520),r2=w2s(2050,1150);ctx.beginPath();ctx.moveTo(r1.x,r1.y);ctx.quadraticCurveTo(W*.55,H*.45,r2.x,r2.y);ctx.stroke();}
function bar(e){if(e.hp===undefined||e.hp<=0)return;let s=w2s(e.x,e.y-e.r-13),ww=Math.max(30,e.r*2.05*state.camera.zoom);ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(s.x-ww/2,s.y,ww,5);ctx.fillStyle=e.team==='player'?'#5fe879':'#ff5548';ctx.fillRect(s.x-ww/2,s.y,ww*clamp(e.hp/e.maxHp,0,1),5)}
function resbar(o){if(o.resource===undefined||o.resource<=0)return;let s=w2s(o.x,o.y+o.r+8),ww=Math.max(34,o.r*1.55*state.camera.zoom);ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(s.x-ww/2,s.y,ww,4);ctx.fillStyle='#d8a94a';ctx.fillRect(s.x-ww/2,s.y,ww*clamp(o.resource/o.maxResource,0,1),4)}
function drawObj(o){if(o.hp!==undefined&&o.hp<=0)return;let s=w2s(o.x,o.y),r=o.r*state.camera.zoom;ctx.save();ctx.translate(s.x,s.y);if(o.type==='tree'){if(o.resource<=0){ctx.fillStyle='#6b4b2d';ctx.beginPath();ctx.ellipse(0,0,r*.5,r*.36,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b88b53';ctx.lineWidth=Math.max(1,r*.08);ctx.beginPath();ctx.arc(0,0,r*.23,0,Math.PI*2);ctx.stroke()}else{ctx.fillStyle='#392313';ctx.fillRect(-r*.16,r*.04,r*.32,r*.62);ctx.fillStyle=['#153f1b','#1e5322','#234b1e'][o.var||0];ctx.beginPath();ctx.arc(0,-r*.15,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(67,125,48,.6)';ctx.beginPath();ctx.arc(-r*.24,-r*.3,r*.52,0,Math.PI*2);ctx.fill()}}else if(o.type==='mine'){ctx.fillStyle=o.resource>0?'#5d5b51':'#3c3b36';ctx.beginPath();ctx.ellipse(0,r*.05,r,r*.72,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=o.resource>0?'#211b14':'#1a1714';ctx.beginPath();ctx.arc(-r*.12,0,r*.55,Math.PI,0);ctx.lineTo(r*.43,r*.45);ctx.lineTo(-r*.66,r*.45);ctx.closePath();ctx.fill();if(o.resource>0){ctx.fillStyle='#e0b95e';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc((i-2)*r*.18,r*.48+(i%2)*r*.06,r*.08,0,Math.PI*2);ctx.fill()}}}else if(o.type==='keep'){ctx.fillStyle='#837b6b';ctx.fillRect(-r*.86,-r*.62,r*1.72,r*1.25);ctx.fillStyle='#334f99';ctx.beginPath();ctx.moveTo(-r*.62,-r*1.05);ctx.lineTo(-r*.42,-r*1.38);ctx.lineTo(-r*.22,-r*1.05);ctx.fill();ctx.beginPath();ctx.moveTo(r*.22,-r*1.05);ctx.lineTo(r*.42,-r*1.38);ctx.lineTo(r*.62,-r*1.05);ctx.fill();ctx.fillStyle='#25180f';ctx.fillRect(-r*.23,r*.07,r*.46,r*.57)}else if(o.type==='farm'){ctx.fillStyle='#8a6733';ctx.fillRect(-r,-r*.48,r*1.85,r);ctx.fillStyle='#2e5f29';for(let i=-3;i<=3;i++)ctx.fillRect(i*r*.25,r*.45,r*.09,r*.55);ctx.fillStyle='#2b4f94';ctx.beginPath();ctx.moveTo(-r,-r*.48);ctx.lineTo(-r*.08,-r*1.08);ctx.lineTo(r*.84,-r*.48);ctx.fill()}else if(o.type==='slaughterhouse'){ctx.fillStyle='#3d1d17';ctx.fillRect(-r,-r*.5,r*1.9,r*1.1);ctx.fillStyle='#111';ctx.beginPath();ctx.moveTo(-r,-r*.5);ctx.lineTo(-r*.05,-r*1.14);ctx.lineTo(r*.9,-r*.5);ctx.fill();ctx.fillStyle='#b12d24';ctx.fillRect(-r*.2,r*.05,r*.35,r*.5)}else if(o.type==='tower'){ctx.fillStyle='#69675f';ctx.fillRect(-r*.43,-r*.95,r*.86,r*1.58);ctx.fillStyle='#2f4f9a';ctx.beginPath();ctx.moveTo(-r*.74,-r*.95);ctx.lineTo(0,-r*1.36);ctx.lineTo(r*.74,-r*.95);ctx.fill()}else if(o.type==='camp'){ctx.fillStyle='#351b18';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.moveTo(-r*.72,r*.25);ctx.lineTo(0,-r*.95);ctx.lineTo(r*.72,r*.25);ctx.fill();ctx.fillStyle='#c53c2b';ctx.beginPath();ctx.arc(0,-r*.1,r*.18,0,Math.PI*2);ctx.fill()}ctx.restore();bar(o);resbar(o)}
function drawUnit(u){if(u.hp<=0)return;let s=w2s(u.x,u.y),r=u.r*state.camera.zoom;ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(0,r*.48,r*.9,r*.34,0,0,Math.PI*2);ctx.fill();if(u.selected){ctx.strokeStyle='#41c7ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,r+8,0,Math.PI*2);ctx.stroke()}let player=u.team==='player',blue=player?'#2c63bd':'#b12b25',metal=player?'#d8d4bd':'#2b2b2b',leather=player?'#7d512c':'#1c1110';if(u.type==='cavalry'||u.type==='warg'){ctx.fillStyle=u.type==='warg'?'#3b2e2b':'#5b3b25';ctx.beginPath();ctx.ellipse(0,r*.08,r*1.25,r*.6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=blue;ctx.beginPath();ctx.arc(-r*.15,-r*.38,r*.42,0,Math.PI*2);ctx.fill();ctx.fillStyle=metal;ctx.fillRect(r*.22,-r*.78,r*.85,r*.13)}else{ctx.fillStyle=blue;ctx.beginPath();ctx.arc(0,-r*.15,r*.65,0,Math.PI*2);ctx.fill();ctx.fillStyle=metal;ctx.beginPath();ctx.arc(0,-r*.72,r*.3,0,Math.PI*2);ctx.fill();if(u.type==='worker'){ctx.fillStyle=leather;ctx.fillRect(r*.15,-r*.95,r*.17,r*1.35)}else if(u.type==='spear'||u.type==='impaler'){ctx.fillStyle='#16100b';ctx.fillRect(r*.25,-r*1.25,r*.1,r*2.25);ctx.fillStyle=metal;ctx.beginPath();ctx.moveTo(r*.3,-r*1.45);ctx.lineTo(r*.05,-r);ctx.lineTo(r*.55,-r);ctx.fill()}else if(u.type==='archer'||u.type==='darkarcher'){ctx.strokeStyle='#1b120b';ctx.lineWidth=Math.max(2,r*.16);ctx.beginPath();ctx.arc(r*.2,-r*.05,r*.65,-1.2,1.2);ctx.stroke()}else{ctx.fillStyle=metal;ctx.fillRect(r*.15,-r*.2,r,r*.15);ctx.fillStyle='rgba(255,255,255,.58)';ctx.beginPath();ctx.arc(-r*.45,-r*.1,r*.34,0,Math.PI*2);ctx.fill()}}ctx.restore();bar(u)}
function drawFx(){for(const e of fx){if(e.kind==='arrow'||e.kind==='bolt'){let a=w2s(e.x,e.y),b=w2s(e.tx,e.ty);ctx.strokeStyle=e.kind==='bolt'?'#ffe39b':'#f8f1c2';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}else{let s=w2s(e.x,e.y);ctx.fillStyle=e.kind==='gain'?`rgba(255,220,100,${clamp(e.life*2,0,1)})`:e.m>1?`rgba(80,255,110,${clamp(e.life*2,0,1)})`:e.m<1?`rgba(255,90,70,${clamp(e.life*2,0,1)})`:`rgba(255,230,140,${clamp(e.life*2,0,1)})`;ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText(e.text,s.x,s.y-(1-e.life)*24)}}}
function drawPlacement(){if(state.mode!=='placefarm'&&state.mode!=='placetower')return;let w=lastPointer||s2w(W/2,H/2),s=w2s(w.x,w.y),r=(state.mode==='placefarm'?48:38)*state.camera.zoom;ctx.strokeStyle='rgba(255,224,112,.95)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(255,224,112,.25)';ctx.beginPath();ctx.arc(s.x,s.y,280*state.camera.zoom,0,Math.PI*2);ctx.stroke()}
function drawDrag(){if(!state.drag)return;let r=state.drag;ctx.strokeStyle='#41c7ff';ctx.fillStyle='rgba(65,199,255,.12)';ctx.lineWidth=2;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillRect(r.x,r.y,r.w,r.h)}
function drawMini(){mctx.clearRect(0,0,MW,MH);mctx.save();mctx.beginPath();mctx.arc(MW/2,MH/2,Math.min(MW,MH)/2-2,0,Math.PI*2);mctx.clip();mctx.fillStyle='#1d3318';mctx.fillRect(0,0,MW,MH);let px=x=>x/state.mapW*MW,py=y=>y/state.mapH*MH;for(const o of objects){if(o.hp!==undefined&&o.hp<=0)continue;if(o.type==='tree'&&o.resource<=0)continue;mctx.fillStyle=o.type==='tree'?'#2d7a2d':o.type==='mine'?'#d8a94a':o.team==='enemy'?'#e04b38':'#e6d28f';let sz=o.type==='keep'||o.type==='camp'?5:3;mctx.fillRect(px(o.x)-sz/2,py(o.y)-sz/2,sz,sz)}for(const u of units){if(u.hp<=0)continue;mctx.fillStyle=u.team==='enemy'?'#ff4a3d':'#3aa9ff';mctx.fillRect(px(u.x)-2,py(u.y)-2,4,4)}let tl=s2w(0,0),br=s2w(W,H);mctx.strokeStyle='#fff0a0';mctx.lineWidth=1;mctx.strokeRect(px(tl.x),py(tl.y),px(br.x)-px(tl.x),py(br.y)-py(tl.y));mctx.restore();mctx.strokeStyle='rgba(255,220,130,.7)';mctx.lineWidth=2;mctx.beginPath();mctx.arc(MW/2,MH/2,Math.min(MW,MH)/2-2,0,Math.PI*2);mctx.stroke()}
function render(){ctx.clearRect(0,0,W,H);ground();[...objects,...units].sort((a,b)=>(a.y||0)-(b.y||0)).forEach(x=>units.includes(x)?drawUnit(x):drawObj(x));drawFx();drawPlacement();drawDrag();drawMini()}
let ts={pan:false,drag:false,lastX:0,lastY:0,startX:0,startY:0,startTime:0,pinch:0,zoom:1,mid:null};
canvas.addEventListener('touchstart',e=>{e.preventDefault();if(e.touches.length===1){let t=e.touches[0];ts.pan=true;ts.drag=false;ts.lastX=ts.startX=t.clientX;ts.lastY=ts.startY=t.clientY;ts.startTime=performance.now();lastPointer=s2w(t.clientX,t.clientY)}else if(e.touches.length===2){let a=e.touches[0],b=e.touches[1];ts.pinch=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);ts.zoom=state.camera.zoom;ts.mid={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};ts.drag=false;state.drag=null}}, {passive:false});
canvas.addEventListener('touchmove',e=>{e.preventDefault();if(e.touches.length===1&&ts.pan){let t=e.touches[0],dx=t.clientX-ts.lastX,dy=t.clientY-ts.lastY;lastPointer=s2w(t.clientX,t.clientY);state.camera.x-=dx/state.camera.zoom;state.camera.y-=dy/state.camera.zoom;state.camera.x=clamp(state.camera.x,0,state.mapW);state.camera.y=clamp(state.camera.y,0,state.mapH);ts.lastX=t.clientX;ts.lastY=t.clientY}else if(e.touches.length===2){let a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),mid={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};lastPointer=s2w(mid.x,mid.y);let ratio=d/Math.max(1,ts.pinch),move=Math.hypot(mid.x-ts.mid.x,mid.y-ts.mid.y);if(Math.abs(ratio-1)>.08)state.camera.zoom=clamp(ts.zoom*ratio,.55,2.35);else if(move>18){ts.drag=true;state.drag={x:Math.min(ts.mid.x,mid.x),y:Math.min(ts.mid.y,mid.y),w:Math.abs(mid.x-ts.mid.x),h:Math.abs(mid.y-ts.mid.y)}}}}, {passive:false});
canvas.addEventListener('touchend',e=>{e.preventDefault();if(e.touches.length)return;if(ts.drag&&state.drag){selectRect(state.drag);state.drag=null;ts.drag=false;return}let moved=Math.hypot(ts.lastX-ts.startX,ts.lastY-ts.startY),elapsed=performance.now()-ts.startTime;if(moved<12&&elapsed<380)tap(ts.startX,ts.startY);ts.pan=false}, {passive:false});
canvas.addEventListener('mousemove',e=>lastPointer=s2w(e.clientX,e.clientY));canvas.addEventListener('click',e=>tap(e.clientX,e.clientY));
function selectRect(r){let list=playerUnits().filter(u=>{let s=w2s(u.x,u.y);return s.x>=r.x&&s.x<=r.x+r.w&&s.y>=r.y&&s.y<=r.y+r.h});list.length?select(list):msg('No units in selection box.')}
function tap(sx,sy){let w=s2w(sx,sy);lastPointer=w;if(state.mode==='placefarm'||state.mode==='placetower'){place(state.mode==='placefarm'?'farm':'tower',w.x,w.y);return}let hp=hit(w,'player'),he=hit(w,'enemy'),ha=hit(w);if(state.mode==='attack'){if(he){attackGroup(he);state.mode='normal';refresh()}else msg('Attack mode: tap enemy target.');return}if(hp&&units.includes(hp)){select([hp]);return}if(state.selected.length){if(he)attackGroup(he);else if(ha&&ha.type==='tree'){let workers=state.selected.filter(u=>u.type==='worker');workers.forEach(u=>{u.target=ha;u.task='chop'});msg(workers.length?`${workers.length} worker(s) chopping selected tree.`:'Only workers can gather.')}else if(ha&&ha.type==='mine'){let workers=state.selected.filter(u=>u.type==='worker');workers.forEach(u=>{u.target=ha;u.task='mine'});msg(workers.length?`${workers.length} worker(s) mining Resource.`:'Only workers can mine.')}else moveGroup(w.x,w.y)}else msg(he?`${he.name||he.type}: enemy target.`:'Tap or two-finger drag to select your units.')}
mini.addEventListener('touchstart',e=>{e.preventDefault();let r=mini.getBoundingClientRect(),t=e.touches[0];state.camera.x=clamp((t.clientX-r.left)/r.width*state.mapW,0,state.mapW);state.camera.y=clamp((t.clientY-r.top)/r.height*state.mapH,0,state.mapH)}, {passive:false});
function loop(t){let dt=Math.min(.05,(t-state.last)/1000||0);state.last=t;update(dt);render();requestAnimationFrame(loop)}
msg('V3 ready: one Resource, farms, mines, chopped trees, and balanced combat counters.');requestAnimationFrame(loop);
})();
